name: SubParse Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  attempt_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint and build
        run: npm run lint && npm run build
